### ISSUE TITLE
Config file not found

### ISSUE THREAD

**Issue by naresh3212** [frankfoerster/tipsy#2]
When using the migration command, the error is throwing:

**Could not load configuration file: D:\xampp\htdocs\tipsy\config\app.php**

I can not find the file inside _Config_ directory.

I followed your Environment settings and it's still not working.

**Comment by frankfoerster** [comment]
Hello @naresh3212,
the app.php configuration file is usually created automatically by running `composer install`.

If it is missing in your setup, you can manually run `composer run-script post-install-cmd` from your cmd.

Cheers Frank
